from . import _version
from .core import (
    ks_2samp_2d,
)
from .scipy import (
    anderson_ksamp,
    ansari,
    bartlett,
    brunnermunzel,
    cramervonmises,
    cramervonmises_2samp,
    epps_singleton_2samp,
    fligner,
    friedmanchisquare,
    jarque_bera,
    kruskal,
    ks_1samp_1d,
    ks_2samp_1d,
    kurtosistest,
    levene,
    mannwhitneyu,
    median_test,
    mood,
    normaltest,
    ranksums,
    shapiro,
    skewtest,
    ttest_ind,
    ttest_rel,
)

__version__ = _version.get_versions()["version"]

__all__ = [
    "anderson_ksamp",
    "ansari",
    "bartlett",
    "brunnermunzel",
    "cramervonmises",
    "cramervonmises_2samp",
    "epps_singleton_2samp",
    "fligner",
    "friedmanchisquare",
    "jarque_bera",
    "kruskal",
    "ks_1samp_1d",
    "ks_2samp_1d",
    "ks_2samp_2d",
    "kurtosistest",
    "levene",
    "mannwhitneyu",
    "median_test",
    "mood",
    "normaltest",
    "ranksums",
    "shapiro",
    "skewtest",
    "ttest_ind",
    "ttest_rel",
]
